### ISSUE TITLE
A lot of the tests in gexml fail. Maybe you can have a look at it too? The traceback is always similar (the entry point just differs)

### ISSUE THREAD

**Issue by ampledata** [ampledata/gexml#1]
From @dleidert: 

```
======================================================================
ERROR: test_[..]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/gexml-eYnPjM/gexml-1.0.0/gexml/__init__.py", line 569, in _make_xml_node
    ntype = xml.nodeType
AttributeError: 'str' object has no attribute 'nodeType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/gexml-eYnPjM/gexml-1.0.0/gexml/__init__.py", line 581, in _make_xml_node
    xml_attributes = xml_declaration.group('xml_attributes')
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[..]
  File "/build/gexml-eYnPjM/gexml-1.0.0/gexml/__init__.py", line 294, in parse
    node = self._make_xml_node(xml)
  File "/build/gexml-eYnPjM/gexml-1.0.0/gexml/__init__.py", line 592, in _make_xml_node
    raise XmlError(e)
gexml.XmlError: 'NoneType' object has no attribute 'group'
```

**Comment by ampledata** [comment]
From @dleidert:

> It seems the issue is related to this first pattern search here: https://github.com/ampledata/gexml/blob/master/gexml/__init__.py#L580-L581. If I remove these lines and only apply the second pattern (like in the dexml) the tests work. I would really appreciate your response.

**Comment by ampledata** [comment]
From @dleidert:

> I've written a patch for the gexml issue. It kind of restores the old behavior if the first pattern search leads to no results:
https://salsa.debian.org/dleidert/gexml/-/blob/debian/sid/debian/patches/backwards-compatibility.patch
